// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'package:firebase_core/firebase_core.dart';
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDvsCQsTU_zJ6FtExNzrmyGvB-WZxXBiwM',
    appId: '1:696251934954:web:bb456f883a6b15fa9a0f93',
    messagingSenderId: '696251934954',
    projectId: 'online-store-e5224',
    authDomain: 'online-store-e5224.firebaseapp.com',
    storageBucket: 'online-store-e5224.appspot.com',
    measurementId: 'G-M7G88NZSC0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7ak0S5SpF9SvxP36xMh5AW5_gGvZuzpo',
    appId: '1:696251934954:android:4dd073876ffeb2539a0f93',
    messagingSenderId: '696251934954',
    projectId: 'online-store-e5224',
    storageBucket: 'online-store-e5224.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCMtDKxsv9ar5bvq-iAkfhU3rz5D1SIZdw',
    appId: '1:696251934954:ios:7d9bb72974ae2f509a0f93',
    messagingSenderId: '696251934954',
    projectId: 'online-store-e5224',
    storageBucket: 'online-store-e5224.appspot.com',
    iosBundleId: 'com.juliana.onlineStore',
  );
}
